import './js/mobile-menu';
// import './js/scroll';
import './js/theme-changer';
import './js/render/render-search-letters';
import './js/cocktails';
import './js/user-screen-width-follower';
import './js/fetch/get-random-cockt';
import './js/render/render-coctails-cards';
import './js/fetch/get-cocktails-by-search';
import './js/modal/modal-cocktail';
import './js/modal/modal-ingredient';
import './js/render/render-modal-ingred';
import './js/element-pagination';
// import './js/favor-cockt';
import './js/init-search';
import './js/favor-cocktails-addListenerBtn';
import './js/check-elem-in-loc-stor';
